import { createWorkspace } from "./actions"
import { createClient } from "@/lib/supabase/server"
import { listMyInvitations } from "@/lib/invitations"
import { respondToInvitation } from "@/app/(dashboard)/invites/actions"

export default async function OnboardingPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams
  // People invited before they had any workspace land here, so offer their invitations first.
  const invitations = await listMyInvitations(await createClient())
  return <main className="flex min-h-screen items-center justify-center px-4 py-10"><section className="surface w-full max-w-md p-6 sm:p-8"><div className="flex items-center gap-3"><span className="brand-mark">SC</span><div><p className="font-semibold tracking-tight">Sanctum Cove</p><p className="text-xs text-zinc-500">A calm place to begin</p></div></div>{invitations.length > 0 && <div className="mt-8 space-y-2"><p className="text-sm font-semibold">You have {invitations.length === 1 ? "an invitation" : invitations.length + " invitations"}</p>{invitations.map((invitation) => <form key={invitation.id} action={respondToInvitation} className="flex flex-wrap items-center gap-2 rounded-xl border border-[var(--line)] p-3 text-sm"><input type="hidden" name="id" value={invitation.id} /><input type="hidden" name="returnTo" value="/onboarding" /><span className="min-w-0 flex-1">Join <strong>{invitation.workspace_name}</strong> as {invitation.role === "admin" ? "an admin" : "a member"}</span><button name="decision" value="decline" className="button-secondary min-h-0 px-3 py-1.5 text-xs">Decline</button><button name="decision" value="accept" className="button-primary min-h-0 px-3 py-1.5 text-xs">Accept</button></form>)}<p className="pt-2 text-xs text-[var(--muted)]">Or create your own workspace below.</p></div>}<div className="mt-10"><p className="eyebrow">Step 1 of 1</p><h1 className="page-title">Create your workspace</h1><p className="page-description">Your workspace keeps data and collaboration together.</p></div>{error && <p role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form action={createWorkspace} className="form-grid mt-8"><label className="field-label">Workspace name<input required name="name" className="field-control" placeholder="My workspace" /></label><label className="field-label">Workspace slug<input required name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className="field-control" placeholder="my-workspace" /></label><button className="button-primary w-full">Create workspace</button></form></section></main>
}
