"use client"

import { useEffect, useMemo, useState } from "react"

type NoteAction = (formData: FormData) => Promise<void>

function renderMarkdown(content: string) { return content.split("\n").map((line, index) => { const key = line + index; if (line.startsWith("# ")) return <h3 key={key} className="text-lg font-semibold">{line.slice(2)}</h3>; if (line.startsWith("## ")) return <h4 key={key} className="font-semibold">{line.slice(3)}</h4>; if (line.startsWith("- ")) return <li key={key} className="ml-5 list-disc">{line.slice(2)}</li>; const parts = line.split("**"); return <p key={key} className="min-h-6">{parts.map((part, partIndex) => partIndex % 2 ? <strong key={partIndex}>{part}</strong> : part)}</p> }) }

export function NoteComposer({ action }: { action: NoteAction }) {
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [folder, setFolder] = useState("General"); const [tags, setTags] = useState(""); const [preview, setPreview] = useState(false); const [saved, setSaved] = useState(false)
  const commands = ["/heading", "/todo", "/bullet"]
  useEffect(() => { const draft = window.localStorage.getItem("lifehub:note-draft"); if (!draft) return; try { const parsed = JSON.parse(draft) as { title?: string; content?: string; folder?: string; tags?: string }; setTitle(parsed.title ?? ""); setContent(parsed.content ?? ""); setFolder(parsed.folder ?? "General"); setTags(parsed.tags ?? "") } catch { window.localStorage.removeItem("lifehub:note-draft") } }, [])
  useEffect(() => { if (!title && !content && folder === "General" && !tags) return; window.localStorage.setItem("lifehub:note-draft", JSON.stringify({ title, content, folder, tags })); setSaved(true); const timeout = window.setTimeout(() => setSaved(false), 1200); return () => window.clearTimeout(timeout) }, [content, folder, tags, title])
  const slashVisible = useMemo(() => content.endsWith("/") || content.split("\n").some((line) => line.trim() === "/"), [content]); const insertCommand = (command: string) => setContent((value) => value.replace(/\/?$/, command + " "))
  return <form action={action} onSubmit={() => window.localStorage.removeItem("lifehub:note-draft")} className="form-grid mt-5"><div className="grid gap-3 sm:grid-cols-[1fr_0.45fr]"><label className="field-label">Title<input required name="title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What are you thinking about?" className="field-control" /></label><label className="field-label">Folder<select name="folder" value={folder} onChange={(event) => setFolder(event.target.value)} className="field-control"><option>General</option><option>Ideas</option><option>Projects</option><option>Personal</option></select></label></div><label className="field-label">Tags<input name="tags" value={tags} onChange={(event) => setTags(event.target.value)} placeholder="design, planning" className="field-control" /><span className="text-xs font-normal text-zinc-400">Separate tags with commas.</span></label><div className="toolbar"><div className="flex gap-1 rounded-lg bg-zinc-100 p-1"><button type="button" onClick={() => setPreview(false)} className={preview ? "button-quiet min-h-0 px-3 py-1.5 text-xs" : "button-secondary min-h-0 px-3 py-1.5 text-xs"}>Write</button><button type="button" onClick={() => setPreview(true)} className={preview ? "button-secondary min-h-0 px-3 py-1.5 text-xs" : "button-quiet min-h-0 px-3 py-1.5 text-xs"}>Preview</button></div><span className="text-xs text-zinc-400">{saved ? "Draft saved" : "Autosave on"}</span></div>{preview ? <div className="surface-muted min-h-40 p-4 text-sm leading-7 text-zinc-700">{content ? renderMarkdown(content) : <span className="text-zinc-400">Preview your Markdown here.</span>}</div> : <div><textarea name="content" value={content} onChange={(event) => setContent(event.target.value)} placeholder="Write something… Use # heading, **bold**, or / commands." className="field-control min-h-32 resize-y" />{slashVisible && <div className="mt-2 flex flex-wrap items-center gap-2 rounded-lg border bg-white p-2 text-xs"><span className="text-zinc-500">Insert command</span>{commands.map((command) => <button key={command} type="button" onClick={() => insertCommand(command)} className="button-secondary min-h-0 px-2 py-1 text-xs">{command}</button>)}</div>}</div>}<button className="button-primary w-fit">Add note</button></form>
}
