"use client"

import { useEffect, useState } from "react"
import { Select } from "@/components/ui/select"

import { NoteEditor } from "@/components/note-editor"
import { useImageUpload } from "@/hooks/use-image-upload"

type NoteAction = (formData: FormData) => Promise<void>

export function NoteComposer({ action, workspaceId }: { action: NoteAction; workspaceId: string }) {
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [folder, setFolder] = useState("General"); const [tags, setTags] = useState(""); const [saved, setSaved] = useState(false); const [preview, setPreview] = useState(false); const [processing, setProcessing] = useState(false)
  const { processImages } = useImageUpload()
  useEffect(() => { const draft = window.localStorage.getItem("lifehub:note-draft"); if (!draft) return; try { const parsed = JSON.parse(draft) as { title?: string; content?: string; folder?: string; tags?: string }; setTitle(parsed.title ?? ""); setContent(parsed.content ?? ""); setFolder(parsed.folder ?? "General"); setTags(parsed.tags ?? "") } catch { window.localStorage.removeItem("lifehub:note-draft") } }, [])
  useEffect(() => { if (!title && !content && folder === "General" && !tags) return; window.localStorage.setItem("lifehub:note-draft", JSON.stringify({ title, content, folder, tags })); setSaved(true); const timeout = window.setTimeout(() => setSaved(false), 1200); return () => window.clearTimeout(timeout) }, [content, folder, tags, title])
  return <form action={action} onSubmit={async (event) => { event.preventDefault(); setPreview(false); setProcessing(true); try { const formData = new FormData(event.currentTarget); formData.set("content", await processImages(content, workspaceId)); window.localStorage.removeItem("lifehub:note-draft"); await action(formData) } catch { setSaved(false) } finally { setProcessing(false) } }} className="form-grid mt-5"><div className="grid gap-3 sm:grid-cols-[1fr_0.45fr]"><label className="field-label">Title<input required name="title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What are you thinking about?" className="field-control" /></label><label className="field-label">Folder<Select name="folder" value={folder} onChange={setFolder} options={[{ value: "General", label: "General" }, { value: "Ideas", label: "Ideas" }, { value: "Projects", label: "Projects" }, { value: "Personal", label: "Personal" }]} /></label></div><label className="field-label">Tags<input name="tags" value={tags} onChange={(event) => setTags(event.target.value)} placeholder="design, planning" className="field-control" /><span className="text-xs font-normal text-zinc-400">Separate tags with commas.</span></label><div className="toolbar"><div className="flex gap-1 rounded-lg bg-zinc-100 p-1"><button type="button" onClick={() => setPreview(false)} className={preview ? "button-quiet min-h-0 px-3 py-1.5 text-xs" : "button-secondary min-h-0 px-3 py-1.5 text-xs"}>Write</button><button type="button" onClick={() => setPreview(true)} className={preview ? "button-secondary min-h-0 px-3 py-1.5 text-xs" : "button-quiet min-h-0 px-3 py-1.5 text-xs"}>Preview</button></div><span className="text-xs text-zinc-400">{processing ? "Uploading images…" : saved ? "Draft saved" : "Autosave on"}</span></div>{preview ? <iframe title="Note preview" sandbox="" height={240} className="tiptap-editor tiptap-preview min-h-32 w-full" srcDoc={`<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' data: https:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><style>body{font-family:system-ui,sans-serif;margin:16px;overflow-wrap:anywhere}img{max-width:100%;height:auto}pre{white-space:pre-wrap}</style></head><body>${content || "<p>Nothing to preview yet.</p>"}</body></html>`} /> : <NoteEditor value={content} onChange={setContent} workspaceId={workspaceId} placeholder="Write something… Use # heading, **bold**, or / commands." height={240} />}<input type="hidden" name="content" value={content} /><button className="button-primary w-fit">Add note</button></form>
}
