"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { accents, applyCustomizePreferences, defaultCustomizePreferences, readCustomizePreferences, type CustomizePreferences } from "@/lib/customize"

type Section = "general" | "appearance" | "workspace" | "notifications" | "security" | "integrations" | "billing" | "backup" | "danger"
type Props = { workspace: { name: string; slug: string }; driveConnected: boolean; canManageDrive: boolean }
const sections: Array<[Section, string, string]> = [["general", "General", "Language, date, and time"], ["appearance", "Appearance", "Theme and interface"], ["workspace", "Workspace", "Identity and members"], ["notifications", "Notifications", "Delivery preferences"], ["security", "Security", "Password and sessions"], ["integrations", "Integrations", "Connected services"], ["billing", "Billing", "Plan and invoices"], ["backup", "Backup", "Export and recovery"], ["danger", "Danger Zone", "Permanent actions"]]

export function SettingsStudio({ workspace, driveConnected, canManageDrive }: Props) {
  const [section, setSection] = useState<Section>("general")
  const [preferences, setPreferences] = useState(defaultCustomizePreferences)
  const [saved, setSaved] = useState("")
  const [general, setGeneral] = useState({ language: "English", timezone: "Asia/Jakarta", dateFormat: "DD/MM/YYYY", timeFormat: "24-hour" })
  const active = useMemo(() => sections.find(([key]) => key === section)!, [section])

  useEffect(() => setPreferences(readCustomizePreferences()), [])
  function save() { applyCustomizePreferences(preferences); window.localStorage.setItem("lifehub:settings-general", JSON.stringify(general)); setSaved("Saved in this browser") }
  function changePreferences(next: CustomizePreferences) { setPreferences(next); applyCustomizePreferences(next); setSaved("Preview updated") }

  const appearance = <div className="space-y-6"><div><p className="eyebrow">Theme</p><div className="mt-3 flex flex-wrap gap-2">{(["light", "dark", "system"] as const).map((theme) => <button key={theme} type="button" onClick={() => changePreferences({ ...preferences, theme })} className={preferences.theme === theme ? "button-primary min-h-0 px-3 py-2 capitalize" : "button-secondary min-h-0 px-3 py-2 capitalize"}>{theme}</button>)}</div></div><label className="field-label">Accent color<select value={preferences.accent} onChange={(event) => changePreferences({ ...preferences, accent: event.target.value as keyof typeof accents })} className="field-control">{Object.entries(accents).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Density<select value={preferences.density} onChange={(event) => changePreferences({ ...preferences, density: event.target.value as "comfortable" | "compact" })} className="field-control"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label className="field-label">Corner radius<select value={preferences.radius} onChange={(event) => changePreferences({ ...preferences, radius: Number(event.target.value) })} className="field-control"><option value="10">Small</option><option value="16">Medium</option><option value="22">Large</option></select></label></div><Link href="/customize" className="button-secondary w-fit">Open full customization studio</Link></div>
  const generalContent = <div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Language<select value={general.language} onChange={(event) => setGeneral({ ...general, language: event.target.value })} className="field-control"><option>English</option><option>Bahasa Indonesia</option></select></label><label className="field-label">Timezone<select value={general.timezone} onChange={(event) => setGeneral({ ...general, timezone: event.target.value })} className="field-control"><option>Asia/Jakarta</option><option>UTC</option></select></label><label className="field-label">Date format<select value={general.dateFormat} onChange={(event) => setGeneral({ ...general, dateFormat: event.target.value })} className="field-control"><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></label><label className="field-label">Time format<select value={general.timeFormat} onChange={(event) => setGeneral({ ...general, timeFormat: event.target.value })} className="field-control"><option>24-hour</option><option>12-hour</option></select></label></div>
  const integrations = <div className="space-y-5"><p className="max-w-xl text-sm leading-6 text-zinc-500">Connect Google Drive once for this workspace. Files and profile photos will use the connected Google account without manual refresh-token input.</p><div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-zinc-200/70 p-4"><div><p className="font-semibold">Google Drive</p><p className="mt-1 text-sm text-zinc-500">{driveConnected ? "Connected for this workspace." : "Not connected yet."}</p></div>{canManageDrive ? <Link href="/api/auth/google/login" className="button-primary">{driveConnected ? "Reconnect Google Drive" : "Connect Google Drive"}</Link> : <span className="text-sm text-zinc-500">Ask a workspace admin to connect it.</span>}</div></div>
  const utility = (title: string, description: string, href?: string) => <div className="space-y-4"><p className="max-w-xl text-sm leading-6 text-zinc-500">{description}</p>{href ? <Link href={href} className="button-secondary w-fit">Open {title}</Link> : <p className="rounded-xl bg-[var(--surface-muted)] p-4 text-sm text-zinc-500">This area is ready for the related service when it is connected.</p>}</div>
  const content = section === "general" ? generalContent : section === "appearance" ? appearance : section === "workspace" ? <div className="space-y-5"><div><p className="text-sm font-semibold">{workspace.name}</p><p className="mt-1 text-sm text-zinc-500">lifehub.app/{workspace.slug}</p></div>{utility("Workspace", "Manage members, roles, and workspace identity without crowding the main settings panel.", "/team")}</div> : section === "integrations" ? integrations : section === "notifications" ? utility("Notifications", "Review workspace updates, unread items, and delivery preferences in one focused inbox.", "/notifications") : section === "security" ? utility("Security", "Reset your password and review account access. Two-factor authentication and device sessions will appear here when configured.", "/security") : section === "danger" ? <div className="space-y-4"><p className="text-sm leading-6 text-zinc-500">Destructive workspace actions remain separated from daily preferences.</p><button type="button" className="rounded-xl border border-red-500/40 px-3 py-2 text-sm font-semibold text-red-500">Export data</button></div> : utility(active[1], active[2] + ".")

  return <div className="page-container"><header className="max-w-2xl"><p className="eyebrow">Workspace settings</p><h1 className="page-title">Settings</h1><p className="page-description">One focused panel at a time, with calm defaults and no admin-dashboard noise.</p></header><div className="mt-10 grid gap-8 lg:grid-cols-[13rem_minmax(0,1fr)]"><nav className="settings-nav lg:sticky lg:top-24 lg:h-fit" aria-label="Settings sections">{sections.map(([key, label, description]) => <button key={key} type="button" onClick={() => { setSection(key); setSaved("") }} className={section === key ? "settings-nav-item settings-nav-item-active" : "settings-nav-item"}><span>{label}</span><small>{description}</small></button>)}</nav><section className="settings-panel"><div className="border-b pb-6"><p className="eyebrow">{active[1]}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{active[2]}</h2></div><div className="py-7">{content}</div>{["general", "appearance"].includes(section) && <div className="settings-save-bar"><span role="status" className="text-sm text-zinc-500">{saved || "Changes stay local until saved."}</span><button type="button" onClick={save} className="button-primary">Save changes</button></div>}</section></div></div>
}
