import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const allowedStatuses = new Set(["todo", "in_progress", "done", "cancelled"])
const maxUploadSize = 10 * 1024 * 1024
const allowedMimeTypes = new Set(["image/png", "image/jpeg", "application/pdf", "text/plain"])

assert.equal(slugPattern.test("my-workspace"), true)
assert.equal(slugPattern.test("My Workspace"), false)
assert.equal(allowedStatuses.has("done"), true)
assert.equal(allowedStatuses.has("blocked"), false)
assert.equal(new URL("https://example.com").protocol, "https:")
assert.equal(allowedMimeTypes.has("application/pdf"), true)
assert.equal(maxUploadSize, 10485760)

const foundationsMigration = readFileSync(new URL("../supabase/migrations/0014_backend_foundations.sql", import.meta.url), "utf8")
const advancedMigration = readFileSync(new URL("../supabase/migrations/0015_advanced_module_backend.sql", import.meta.url), "utf8")
const avatarMigration = readFileSync(new URL("../supabase/migrations/0017_profile_avatars.sql", import.meta.url), "utf8")
const dashboardPage = readFileSync(new URL("../src/app/(dashboard)/dashboard/page.tsx", import.meta.url), "utf8")
const notesWorkspace = readFileSync(new URL("../src/components/notes-workspace.tsx", import.meta.url), "utf8")
const storageInterface = readFileSync(new URL("../src/lib/storage/storage.ts", import.meta.url), "utf8")
const filesActions = readFileSync(new URL("../src/app/(dashboard)/files/actions.ts", import.meta.url), "utf8")
const profileActions = readFileSync(new URL("../src/app/(dashboard)/settings/actions.ts", import.meta.url), "utf8")
const storageMigration = readFileSync(new URL("../supabase/migrations/0019_google_drive_storage.sql", import.meta.url), "utf8")
const googleDriveStorage = readFileSync(new URL("../src/lib/storage/google-drive.ts", import.meta.url), "utf8")
const googleOAuthConfig = readFileSync(new URL("../src/lib/google-drive-auth.ts", import.meta.url), "utf8")
const googleOAuthLogin = readFileSync(new URL("../src/app/api/auth/google/login/route.ts", import.meta.url), "utf8")
const googleOAuthCallback = readFileSync(new URL("../src/app/api/auth/google/callback/route.ts", import.meta.url), "utf8")
const workspaceServer = readFileSync(new URL("../src/lib/workspace/server.ts", import.meta.url), "utf8")
const taskActions = readFileSync(new URL("../src/app/(dashboard)/tasks/actions.ts", import.meta.url), "utf8")
const taskDetails = readFileSync(new URL("../src/components/task-details.tsx", import.meta.url), "utf8")
const tasksPage = readFileSync(new URL("../src/app/(dashboard)/tasks/page.tsx", import.meta.url), "utf8")
const calendarActions = readFileSync(new URL("../src/app/(dashboard)/calendar/actions.ts", import.meta.url), "utf8")
const recurrence = readFileSync(new URL("../src/lib/calendar/recurrence.ts", import.meta.url), "utf8")
const reminderRoute = readFileSync(new URL("../src/app/api/calendar/reminders/route.ts", import.meta.url), "utf8")
const calendarMigration = readFileSync(new URL("../supabase/migrations/0021_calendar_reminders.sql", import.meta.url), "utf8")
const vercelConfig = readFileSync(new URL("../vercel.json", import.meta.url), "utf8")
assert.match(foundationsMigration, /profiles are creatable by owner/)
assert.match(foundationsMigration, /members can create file metadata/)
assert.match(foundationsMigration, /accept_workspace_invitation/)
assert.match(advancedMigration, /task_checklist_items/)
assert.match(advancedMigration, /calendar_event_attendees/)
assert.match(advancedMigration, /file_shares/)
assert.match(avatarMigration, /users can upload own avatars/)
assert.match(avatarMigration, /profiles are creatable by owner/)
assert.match(dashboardPage, /Continue working/)
assert.match(dashboardPage, /Workspace health/)
assert.match(notesWorkspace, /Pinned/)
assert.match(notesWorkspace, /Recent/)
assert.match(storageInterface, /interface StorageService/)
assert.match(filesActions, /storage\.upload/)
assert.match(profileActions, /avatar_google_file_id/)
assert.match(storageMigration, /google_file_id/)
assert.doesNotMatch(filesActions, /supabase\.storage/)
assert.doesNotMatch(profileActions, /supabase\.storage/)
assert.match(googleDriveStorage, /Readable\.from\(\[body\]\)/)
assert.match(googleDriveStorage, /responseData/)
assert.match(googleOAuthConfig, /access_type: "offline"/)
assert.match(googleOAuthConfig, /prompt: "consent"/)
assert.doesNotMatch(googleOAuthConfig, /http:\/\/localhost:3000/)
assert.doesNotMatch(googleOAuthLogin, /NODE_ENV === "production"/)
assert.doesNotMatch(googleOAuthCallback, /NODE_ENV === "production"/)
assert.match(googleOAuthCallback, /getToken\(code\)/)
assert.match(googleOAuthCallback, /refresh_token/)
assert.match(workspaceServer, /Could not create activity notifications/)
assert.match(workspaceServer, /recipient_id: member.user_id/)
assert.match(taskActions, /attachTaskFile/)
assert.match(taskActions, /Attached file/)
assert.match(taskDetails, /Attachments/)
assert.match(taskDetails, /Timeline/)
assert.match(tasksPage, /task_attachments/)
assert.match(calendarActions, /addEventAttendee/)
assert.match(calendarActions, /respondEventAttendee/)
assert.match(recurrence, /expandCalendarEvents/)
assert.match(reminderRoute, /CRON_SECRET/)
assert.match(calendarMigration, /reminder_sent_for/)
assert.match(vercelConfig, /api\/calendar\/reminders/)

console.log("LifeHub self-check passed")
