import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { parseCsv } from "../src/lib/csv.mjs"
import { decryptToken, encryptToken } from "../src/lib/token-crypto.mjs"
import { notificationEnabled } from "../src/lib/notification-preferences.mjs"

const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const allowedStatuses = new Set(["todo", "in_progress", "done", "cancelled"])
const maxUploadSize = 10 * 1024 * 1024
const allowedMimeTypes = new Set(["image/png", "image/jpeg", "application/pdf", "text/plain"])

assert.equal(slugPattern.test("my-workspace"), true)
assert.equal(slugPattern.test("My Workspace"), false)
assert.equal(allowedStatuses.has("done"), true)
assert.equal(allowedStatuses.has("blocked"), false)
assert.equal(new URL("https://example.com").protocol, "https:")
assert.equal(allowedMimeTypes.has("application/pdf"), true)
assert.equal(maxUploadSize, 10485760)
assert.deepEqual(parseCsv('title,url,collection,tags\n"A, note","https://example.com","General","work|ideas"\n"Say ""hi""","https://example.com/hi","General",""'), [["title", "url", "collection", "tags"], ["A, note", "https://example.com", "General", "work|ideas"], ['Say "hi"', "https://example.com/hi", "General", ""]])
const encryptedToken = encryptToken("refresh-token", "test-encryption-secret")
assert.notEqual(encryptedToken.includes("refresh-token"), true)
assert.equal(decryptToken(encryptedToken, "test-encryption-secret"), "refresh-token")
assert.equal(notificationEnabled({ tasks_enabled: false }, "task"), false)
assert.equal(notificationEnabled({ tasks_enabled: true }, "task"), true)
assert.equal(notificationEnabled(null, "member"), true)
assert.equal(notificationEnabled(null, "bookmark"), false)

const foundationsMigration = readFileSync(new URL("../supabase/migrations/0014_backend_foundations.sql", import.meta.url), "utf8")
const advancedMigration = readFileSync(new URL("../supabase/migrations/0015_advanced_module_backend.sql", import.meta.url), "utf8")
const avatarMigration = readFileSync(new URL("../supabase/migrations/0017_profile_avatars.sql", import.meta.url), "utf8")
const dashboardPage = readFileSync(new URL("../src/app/(dashboard)/dashboard/page.tsx", import.meta.url), "utf8")
const dashboardLayout = readFileSync(new URL("../src/app/(dashboard)/layout.tsx", import.meta.url), "utf8")
const sidebar = readFileSync(new URL("../src/components/sidebar.tsx", import.meta.url), "utf8")
const notesWorkspace = readFileSync(new URL("../src/components/notes-workspace.tsx", import.meta.url), "utf8")
const storageInterface = readFileSync(new URL("../src/lib/storage/storage.ts", import.meta.url), "utf8")
const filesActions = readFileSync(new URL("../src/app/(dashboard)/files/actions.ts", import.meta.url), "utf8")
const permanentFileDelete = filesActions.slice(filesActions.indexOf("export async function permanentlyDeleteFile"), filesActions.indexOf("export async function uploadFileVersion"))
const profileActions = readFileSync(new URL("../src/app/(dashboard)/settings/actions.ts", import.meta.url), "utf8")
const settingsStudio = readFileSync(new URL("../src/components/settings-studio.tsx", import.meta.url), "utf8")
const settingsPage = readFileSync(new URL("../src/app/(dashboard)/settings/page.tsx", import.meta.url), "utf8")
const storageMigration = readFileSync(new URL("../supabase/migrations/0019_google_drive_storage.sql", import.meta.url), "utf8")
const googleDriveStorage = readFileSync(new URL("../src/lib/storage/google-drive.ts", import.meta.url), "utf8")
const googleOAuthConfig = readFileSync(new URL("../src/lib/google-drive-auth.ts", import.meta.url), "utf8")
const tokenCrypto = readFileSync(new URL("../src/lib/token-crypto.mjs", import.meta.url), "utf8")
const googleOAuthLogin = readFileSync(new URL("../src/app/api/auth/google/login/route.ts", import.meta.url), "utf8")
const googleOAuthCallback = readFileSync(new URL("../src/app/api/auth/google/callback/route.ts", import.meta.url), "utf8")
const workspaceServer = readFileSync(new URL("../src/lib/workspace/server.ts", import.meta.url), "utf8")
const emailHelper = readFileSync(new URL("../src/lib/email.mjs", import.meta.url), "utf8")
const taskActions = readFileSync(new URL("../src/app/(dashboard)/tasks/actions.ts", import.meta.url), "utf8")
const taskDetails = readFileSync(new URL("../src/components/task-details.tsx", import.meta.url), "utf8")
const tasksPage = readFileSync(new URL("../src/app/(dashboard)/tasks/page.tsx", import.meta.url), "utf8")
const calendarActions = readFileSync(new URL("../src/app/(dashboard)/calendar/actions.ts", import.meta.url), "utf8")
const recurrence = readFileSync(new URL("../src/lib/calendar/recurrence.ts", import.meta.url), "utf8")
const reminderRoute = readFileSync(new URL("../src/app/api/calendar/reminders/route.ts", import.meta.url), "utf8")
const workspaceExportRoute = readFileSync(new URL("../src/app/api/workspace/export/route.ts", import.meta.url), "utf8")
const calendarMigration = readFileSync(new URL("../supabase/migrations/0021_calendar_reminders.sql", import.meta.url), "utf8")
const vercelConfig = readFileSync(new URL("../vercel.json", import.meta.url), "utf8")
assert.match(foundationsMigration, /profiles are creatable by owner/)
assert.match(foundationsMigration, /members can create file metadata/)
assert.match(foundationsMigration, /accept_workspace_invitation/)
assert.match(advancedMigration, /task_checklist_items/)
assert.match(advancedMigration, /calendar_event_attendees/)
assert.match(advancedMigration, /file_shares/)
assert.match(avatarMigration, /users can upload own avatars/)
assert.match(avatarMigration, /profiles are creatable by owner/)
assert.match(dashboardPage, /Focus this week/)
assert.match(dashboardPage, /Activity, last 7 days/)
assert.match(dashboardLayout, /workspace_settings/)
assert.match(dashboardLayout, /storageLimitBytes/)
assert.match(sidebar, /counts\.storageLimitBytes/)
assert.doesNotMatch(sidebar, /100 \* 1024 \* 1024 \* 1024/)
assert.match(notesWorkspace, /Pinned/)
assert.match(notesWorkspace, /Recent/)
assert.match(storageInterface, /interface StorageService/)
assert.match(filesActions, /storage\.upload/)
assert.ok(permanentFileDelete.indexOf("getStorageForWorkspace(context.workspaceId).delete") < permanentFileDelete.indexOf('from("files").delete()'))
assert.match(permanentFileDelete, /not\("trashed_at", "is", null\)/)
assert.match(googleDriveStorage, /status === 404/)
assert.match(profileActions, /avatar_google_file_id/)
assert.match(storageMigration, /google_file_id/)
assert.doesNotMatch(filesActions, /supabase\.storage/)
assert.doesNotMatch(profileActions, /supabase\.storage/)
assert.match(googleDriveStorage, /Readable\.from\(\[body\]\)/)
assert.match(googleOAuthConfig, /access_type: "offline"/)
assert.match(googleOAuthConfig, /prompt: "consent"/)
assert.match(tokenCrypto, /createCipheriv/)
assert.match(googleOAuthConfig, /disconnectWorkspaceDriveConnection/)
assert.doesNotMatch(googleOAuthConfig, /console\.error\("Could not revoke Google Drive token", error\)/)
assert.match(googleOAuthConfig, /errorCode === "invalid_token"/)
assert.match(googleOAuthConfig, /throw new Error\("Google token revocation failed"\)/)
assert.match(profileActions, /disconnectGoogleDrive/)
assert.match(settingsStudio, /Disconnect Google Drive/)
assert.match(profileActions, /saveGeneralSettings/)
assert.match(profileActions, /saveNotificationPreferences/)
assert.match(settingsPage, /workspace_settings/)
assert.match(settingsPage, /notification_preferences/)
assert.match(settingsStudio, /initialGeneral/)
assert.match(settingsStudio, /initialNotifications/)
assert.doesNotMatch(settingsStudio, /lifehub:settings-general/)
assert.doesNotMatch(googleOAuthConfig, /http:\/\/localhost:3000/)
assert.doesNotMatch(googleOAuthLogin, /NODE_ENV === "production"/)
assert.doesNotMatch(googleOAuthCallback, /NODE_ENV === "production"/)
assert.match(googleOAuthCallback, /getToken\(code\)/)
assert.match(googleOAuthCallback, /refresh_token/)
assert.match(workspaceServer, /Could not create activity notifications/)
assert.match(workspaceServer, /createAdminClient/)
assert.match(emailHelper, /api\.resend\.com\/emails/)
assert.match(emailHelper, /not_configured/)
assert.doesNotMatch(workspaceServer, /create_workspace_notifications/)
assert.match(taskActions, /attachTaskFile/)
assert.match(taskActions, /Attached file/)
assert.match(taskDetails, /Attachments/)
assert.match(taskDetails, /Timeline/)
assert.match(tasksPage, /task_attachments/)
assert.match(calendarActions, /addEventAttendee/)
assert.match(calendarActions, /respondEventAttendee/)
assert.match(recurrence, /expandCalendarEvents/)
assert.match(reminderRoute, /CRON_SECRET/)
assert.match(workspaceExportRoute, /getWorkspaceContext/)
assert.match(workspaceExportRoute, /workspace_members/)
assert.doesNotMatch(workspaceExportRoute, /refresh_token|token_hash/)
assert.match(settingsStudio, /api\/workspace\/export/)
assert.match(calendarMigration, /reminder_sent_for/)
assert.match(vercelConfig, /api\/calendar\/reminders/)

console.log("LifeHub self-check passed")
